name: Backport trigger
on:
  pull_request:
    types:
      - closed
      - labeled

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger
        run: echo "Triggering workflow"
      - name: Add event payload to summary
        run: |
          echo '### Event Payload' >> $GITHUB_STEP_SUMMARY
          echo '\n```json' >> $GITHUB_STEP_SUMMARY
          cat ${{ github.event_path }} >> $GITHUB_STEP_SUMMARY
          echo '\n```' >> $GITHUB_STEP_SUMMARY
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: event-payload
          path: ${{ github.event_path }}
          retention-days: 1
