name: Backport trigger
on:
  pull_request:
    types:
      - closed
      - labeled

jobs:
  trigger:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      # TODO: save this as job summary instead?
      - name: Trigger
        run: |
          echo "Triggering workflow"
          echo "See https://github.com/${{ github.repository }}/actions/workflows/workflow_run.yml for progress"

      - name: Create action data
        run: |
          jq '{
            action: .action,
            label: .label.name,
            pr_number: .number,
          }' "$GITHUB_EVENT_PATH" > /tmp/backport_data.json

      # The backport action needs access to the 'labelled' event payload, so the event payload is saved
      # as an artifact and downloaded by the backport workflow.
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: event-payload
          path: /tmp/backport_data.json
          retention-days: 1
