name: Backport trigger
on:
  pull_request:
    types:
      - closed
      - labeled

jobs:
  trigger:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Trigger
        run: |
          echo "Triggering workflow"
          echo "See https://github.com/${{ github.repository }}/actions/workflows/workflow_run.yml for progress"
