name: Backport PR Creator (trigger)
on:
  pull_request:
    types:
      - closed
      - labeled

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger
        run: echo "Triggering workflow"
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: payload
          path: ${{ github.event_path }}
          retention-days: 1
