name: Backport workflow
run-name: "Backport workflow for ${{ github.event.workflow_run.head_branch }} #${{ github.event.workflow_run.run_number }}"
on:
  workflow_run:
    workflows: "Backport trigger"
    types:
      - completed

jobs:
  backport:
    # Only run this job if the triggering workflow was not skipped
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      # Just to debug the event payload...
      - name: Add event payload to summary
        run: |
          echo '### Event Payload' >> $GITHUB_STEP_SUMMARY
          echo '```json' >> $GITHUB_STEP_SUMMARY
          echo '' >> $GITHUB_STEP_SUMMARY
          cat ${{ github.event_path }} >> $GITHUB_STEP_SUMMARY
          echo '' >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

      # event.workflow_run.pull_requests contains the PR that triggered the workflow,
      # but it's not populated when the PR comes from a fork for some reason.
      # Instead, use gh cli to get the PR details using the other properties
      - name: Get PR info
        id: pr-info
        env:
          GH_TOKEN: ${{ github.token }}
          PR_TARGET_REPO: ${{ github.repository }}
          PR_BRANCH: |-
            ${{
              (github.event.workflow_run.head_repository.owner.login != github.event.workflow_run.repository.owner.login)
                && format('{0}:{1}', github.event.workflow_run.head_repository.owner.login, github.event.workflow_run.head_branch)
                || github.event.workflow_run.head_branch
            }}
        run: |
          gh pr view --repo "${PR_TARGET_REPO}" "${PR_BRANCH}" \
            --json 'number,headRefOid' \
            --jq '"number=\(.number)\nhead_sha=\(.headRefOid)"' \
            >> $GITHUB_OUTPUT

      - name: Do backport
        env:
          PR_TARGET_REPO: ${{ github.repository }}
          PR_NUMBER: ${{ steps.pr-info.outputs.number }}
        run: |
          echo "Prentend to backport PR ${PR_TARGET_REPO} #${PR_NUMBER} to whatever the labels say"
