name: Backport workflow
run-name: "Backport workflow for ${{ github.event.workflow_run.head_branch }} #${{ github.event.workflow_run.run_number }}"
on:
  workflow_run:
    workflows: "Backport trigger"
    types:
      - completed

jobs:
  backport:
    # Only run this job if the triggering workflow was not skipped
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      # Just to debug the event payload...
      - name: Add event payload to summary
        run: |
          echo '### Event Payload' >> $GITHUB_STEP_SUMMARY
          echo '```json' >> $GITHUB_STEP_SUMMARY
          echo '' >> $GITHUB_STEP_SUMMARY
          cat ${{ github.event_path }} >> $GITHUB_STEP_SUMMARY
          echo '' >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

      # event.workflow_run.pull_requests contains the PR that triggered the workflow,
      # but it's not populated when the PR comes from a fork for some reason.
      # Instead, use gh cli to get the PR details using the other properties
      - name: Download PR info artifact
        uses: actions/download-artifact@v4
        id: download-pr-info
        with:
          run-id: ${{ github.event.workflow_run.id }}
          name: event-payload
          github-token: ${{ github.token }}

      - name: Get PR Info
        id: pr-info
        env:
          PR_INFO_PATH: ${{ steps.download-pr-info.outputs.path }}
          PR_INFO_FILE: ${{ steps.download-pr-info.outputs.path }}/backport_data.json
        run: |
          ls -lah "$PR_INFO_PATH"
          jq -r 'to_entries[] | select(.value | type != "object") | "\(.key)=\(.value)"' "$PR_INFO_FILE" >> $GITHUB_OUTPUT

      - name: Do backport
        env:
          PR_TARGET_REPO: ${{ github.repository }}
          PR_NUMBER: ${{ steps.pr-info.outputs.pr_number }}
          ACTION: ${{ steps.pr-info.outputs.action }}
          LABEL: ${{ steps.pr-info.outputs.label }}
        run: |
          echo "Prentend to backport PR ${PR_TARGET_REPO} #${PR_NUMBER} to whatever the labels say. Action: ${ACTION}, label: ${LABEL}"
