name: Backport workflow
on:
  workflow_run:
    workflows: "Backport trigger"
    types:
      - completed

jobs:
  backport:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger
        run: echo "Triggering workflow"
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: event-payload
          path: ${{ github.event_path }}
          retention-days: 1
